export function textContainAuxiliaryVerbs(word) {
  const splitArray = word.split(" ");
  return (
    auxiliaryVerbs.includes(splitArray[splitArray.length - 1]) ||
    auxiliaryVerbs.includes(splitArray[0])
  );
}

export const auxiliaryVerbs = [
  "do",
  "does",
  "did",
  "can",
  "could",
  "may",
  "might",
  "will",
  "would",
  "am,",
  "is",
  "are",
  "was",
  "were",
  "have",
  "has",
  "had",
  "shall",
  "should",
  "must",
  "not", //"am not","is not","are not","was not","were not","did not", "will not","would not","should not", "shall not", "could not", "might not", "must not"
  "cannot",
  "ain't",
  "isn't",
  "aren't",
  "wasn't",
  "weren't",
  "hasn't",
  "haven't",
  "hadn't",
  "don't",
  "doesn't",
  "didn't",
  "won't",
  "wouldn't",
  "shan't",
  "shouldn't",
  "can't",
  "couldn't",
  "mayn't",
  "mightn't",
  "mustn't",
  "isn’t",
  "mightn’t",
  "mustn’t",
  "needn’t",
  "shan’t",
  "shouldn’t",
  "should’ve",
  "wasn’t",
  "weren’t",
  "won’t",
  "wouldn’t",
  "aren’t",
  "can’t",
  "couldn’t",
  "didn’t",
  "doesn’t",
  "don’t",
  "hadn’t",
  "hasn’t",
  "haven’t",
];
